//Si l'anneau pirate est dans l'inventaire d'un autre joueur que player1, lui rendre !


// Partie 1 : EXTEND TOP dans baldur.bcs, la partie 2 est QQITEM3b EXTEND TOP DPLAYER3.bcs
IF
Global("QQPIRMISSING","GLOBAL",1)
THEN
RESPONSE #100
ActionOverride(Player2,DestroyItem("QQPIR"))
Continue()
END

IF
Global("QQPIRMISSING","GLOBAL",1)
!HasItem("QQPIR",Player2)
THEN
RESPONSE #100
GiveItemCreate("QQPIR",Player1,0,0,0)
SetGlobal("QQPIRMISSING","GLOBAL",0)
Continue()
END